image: node:latest

stages:
  - test
  - deploy_review
  - deploy
  - performance

include:
  - template: Code-Quality.gitlab-ci.yml

test_variable:
  stage: test
  environment:
    name: test
  script:
    - echo neither is $neither
    - echo masked is $masked
    - echo protected is $protected
    - echo both is $both

pages:
  stage: deploy
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn run build

  artifacts:
    paths:
    - public

  only:
  - master
  
deploy_review:
  stage: deploy
  script:
    - yarn install
    - yarn run build
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN
  only:
    - branches
  except:
    - master

performance:
  stage: performance
  image: docker:git
  variables:
    URL: https://mnichols1.gitlab.io/gitpress/
  services:
    - docker:stable-dind
  script:
    - mkdir gitlab-exporter
    - wget -O ./gitlab-exporter/index.js https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js
    - mkdir sitespeed-results
    - docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.3.1 --plugins.add ./gitlab-exporter --outputFolder sitespeed-results $URL
    - mv sitespeed-results/data/performance.json performance.json
  artifacts:
    paths:
      - sitespeed-results/
    reports:
      performance: performance.json
  only:
    variables:
      - $PERFORMANCE == "yes"
    





