image: node:latest

stages:
  - deploy
  - performance

pages:
  stage: deploy
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn run build

  artifacts:
    paths:
    - public

  only:
  - master

performance:
  stage: performance
  image: docker:git
  variables:
    URL: https://mnichols1.gitlab.io/gitpress/
  services:
    - docker:stable-dind
  script:
    - mkdir gitlab-exporter
    - wget -O ./gitlab-exporter/index.js https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js
    - mkdir sitespeed-results
    - docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.3.1 --plugins.add ./gitlab-exporter --outputFolder sitespeed-results $URL
    - mv sitespeed-results/data/performance.json performance.json
  artifacts:
    paths:
      - sitespeed-results/
    reports:
      performance: performance.json
  only:
    - tags



